
openapi: 3.0.0
info:
  title: Device Service API
  version: "1.0"
  description: API for managing devices and availability
paths:
  /api/devices:
    post:
      summary: Create a new device
      tags:
        - Devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        "400":
          description: Invalid input
    get:
      summary: Get all devices with optional filters
      tags:
        - Devices
      responses:
        "200":
          description: List of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  /api/devices/{id}:
    get:
      summary: Get device by ID
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Device found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        "404":
          description: Device not found
    put:
      summary: Update device by ID
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        "200":
          description: Device updated
        "403":
          description: Not found or no permission
    delete:
      summary: Delete device by ID
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Device deleted
        "403":
          description: Not found or no permission
  /api/devices/{id}/availability:
    patch:
      summary: Update device availability
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvailabilityUpdate'
      responses:
        "200":
          description: Availability updated
        "403":
          description: Not found or no permission
    get:
      summary: Get device availability
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Device availability
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        city:
          type: string
        region:
          type: string
        image_url:
          type: string
        available:
          type: boolean
        owner_id:
          type: string
    AvailabilityUpdate:
      type: object
      properties:
        available:
          type: boolean
